
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.4 EDK_O.87xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_D_C_DEVICE_ID,
		XPAR_D_C_BASEADDR,
		XPAR_D_C_INTERRUPT_PRESENT,
		XPAR_D_C_IS_DUAL
	},
	{
		XPAR_LED_DEVICE_ID,
		XPAR_LED_BASEADDR,
		XPAR_LED_INTERRUPT_PRESENT,
		XPAR_LED_IS_DUAL
	},
	{
		XPAR_PUSH_DEVICE_ID,
		XPAR_PUSH_BASEADDR,
		XPAR_PUSH_INTERRUPT_PRESENT,
		XPAR_PUSH_IS_DUAL
	},
	{
		XPAR_ROT_DEVICE_ID,
		XPAR_ROT_BASEADDR,
		XPAR_ROT_INTERRUPT_PRESENT,
		XPAR_ROT_IS_DUAL
	},
	{
		XPAR_RST_DEVICE_ID,
		XPAR_RST_BASEADDR,
		XPAR_RST_INTERRUPT_PRESENT,
		XPAR_RST_IS_DUAL
	},
	{
		XPAR_SCE_DEVICE_ID,
		XPAR_SCE_BASEADDR,
		XPAR_SCE_INTERRUPT_PRESENT,
		XPAR_SCE_IS_DUAL
	}
};


